-- MySQL Script generated by MySQL Workbench
-- Sat Sep  7 16:42:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluno` ;

CREATE TABLE IF NOT EXISTS `Aluno` (
  `CPF` CHAR(11) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NOT NULL,
  `Sexo` TINYINT NULL,
  `DataNascimento` DATETIME NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Area` ;

CREATE TABLE IF NOT EXISTS `Area` (
  `Sigla` VARCHAR(5) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Area_Sigla` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `fk_Area_Area1`
    FOREIGN KEY (`Area_Sigla`)
    REFERENCES `Area` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Area_Area1_idx` ON `Area` (`Area_Sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Curso` ;

CREATE TABLE IF NOT EXISTS `Curso` (
  `Sigla` VARCHAR(5) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Horas` SMALLINT NOT NULL,
  `Custo` FLOAT NULL,
  `Area` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `fk_Curso_Area1`
    FOREIGN KEY (`Area`)
    REFERENCES `Area` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Curso_Area1_idx` ON `Curso` (`Area` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Matricula` ;

CREATE TABLE IF NOT EXISTS `Matricula` (
  `Data` DATETIME NOT NULL,
  `Pago` TINYINT NOT NULL,
  `Curso` VARCHAR(5) NOT NULL,
  `Aluno` CHAR(11) NOT NULL,
  PRIMARY KEY (`Curso`, `Aluno`),
  CONSTRAINT `fk_Matricula_Curso1`
    FOREIGN KEY (`Curso`)
    REFERENCES `Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Aluno1`
    FOREIGN KEY (`Aluno`)
    REFERENCES `Aluno` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Matricula_Curso1_idx` ON `Matricula` (`Curso` ASC) VISIBLE;

CREATE INDEX `fk_Matricula_Aluno1_idx` ON `Matricula` (`Aluno` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Modulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Modulo` ;

CREATE TABLE IF NOT EXISTS `Modulo` (
  `Sigla` VARCHAR(5) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Curso` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `fk_Modulo_Curso`
    FOREIGN KEY (`Curso`)
    REFERENCES `Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Modulo_Curso_idx` ON `Modulo` (`Curso` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Professor` ;

CREATE TABLE IF NOT EXISTS `Professor` (
  `CPF` CHAR(11) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Curso` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`CPF`, `Curso`),
  CONSTRAINT `fk_Professor_Curso1`
    FOREIGN KEY (`Curso`)
    REFERENCES `Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Professor_Curso1_idx` ON `Professor` (`Curso` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Topico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Topico` ;

CREATE TABLE IF NOT EXISTS `Topico` (
  `Sigla` VARCHAR(5) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Horas` SMALLINT NOT NULL,
  `Modulo` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Sigla`, `Modulo`),
  CONSTRAINT `fk_Topico_Modulo1`
    FOREIGN KEY (`Modulo`)
    REFERENCES `Modulo` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Topico_Modulo1_idx` ON `Topico` (`Modulo` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
